apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: crudservice
  name: crudservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crudservice
    spec:
      containers:
      - image: wlanboy/crudservice
        name: crudservice
        ports:
        - containerPort: 8002
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: crudservice-service
  name: crudservice-service
spec:
  selector:
    app: crudservice
  ports:
  - name: 8002-8002
    port: 8002
    protocol: TCP
    targetPort: 8002
  type: LoadBalancer
