apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crudservice-pv-claim
  namespace: crud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
