apiVersion: v1
kind: PersistentVolume
metadata:
  name: crudservice-volume
  labels:
    type: local
  namespace: crud
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/data"
