spring:
  application:
    name: crudservice
  cloud:
    config:
      failFast: false
      uri: http://cloudconfig:8888

server:
  port: ${PORT:8002}

feign:
  hystrix:
    enabled: false
    
userpassword: "$2a$10$QWiocw4XkxxgyayVzY.kkeFV651Rk2xb821MfpXAUMaXbYo1cH7Vm"
usermodpassword: "$2a$10$QWiocw4XkxxgyayVzY.kkeFV651Rk2xb821MfpXAUMaXbYo1cH7Vm"
