spring:
  application:
    name: crudservice
  cloud:
    config:
      failFast: false
      uri: http://cloudconfig:8888

server:
  port: ${PORT:8002}

feign:
  hystrix:
    enabled: false
    
userpassword: "{bcrypt}$2a$04$lyhlD3qw6EIUVAQcglhirOGj2L2gQMVCOShymNNehBBeUL97UvY4O"
usermodpassword: "{bcrypt}$2a$04$lyhlD3qw6EIUVAQcglhirOGj2L2gQMVCOShymNNehBBeUL97UvY4O"
